name: transyte
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  onscreen_num_keyboard: ^1.0.4
  provider: ^6.1.2
  dropdown_textfield: ^1.2.0
  gradient_borders: ^1.0.1
  nested_scroll_view_plus: ^2.0.0
  dropdown_button2: ^2.3.9
  persistent_bottom_nav_bar: ^6.2.1
  flutter_swipe_button: ^2.1.3
  ticket_widget: ^1.0.2
  dotted_line: ^3.2.2
  qr_code_scanner: ^1.0.1
  fl_chart: ^0.69.0
  country_code_picker: ^3.0.0
  defer_pointer: ^0.0.2
  flutter_otp_text_field: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/icon/
